// <auto-generated />
using Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity.Migrations.MySql
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250523180113_MySql_Esquemas")]
    partial class MySql_Esquemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Entity.Model.Form", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("form", "segurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            description = "Formulario para lols Roles",
                            name = "Rol"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            description = "Formulario para los Permisos",
                            name = "Permission"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            description = "Formulario para las Personas",
                            name = "Person"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            description = "Formulario de usuarios",
                            name = "User"
                        },
                        new
                        {
                            id = 5,
                            active = true,
                            description = "Formulario para los modulos",
                            name = "Module"
                        },
                        new
                        {
                            id = 6,
                            active = true,
                            description = "Formulario para los form",
                            name = "FormControllerPrueba"
                        },
                        new
                        {
                            id = 7,
                            active = true,
                            description = "Formulario para los roles que tiene cada usuario",
                            name = "RolUser"
                        },
                        new
                        {
                            id = 8,
                            active = true,
                            description = "Formulario para los formularios que pertenecen a cada modulo",
                            name = "FormModule"
                        },
                        new
                        {
                            id = 9,
                            active = true,
                            description = "Formulario para los roles,formularios y permisos",
                            name = "RolFormPermission"
                        });
                });

            modelBuilder.Entity("Entity.Model.FormModule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("formid")
                        .HasColumnType("int");

                    b.Property<int>("moduleid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("formid");

                    b.HasIndex("moduleid");

                    b.ToTable("formmodule", "segurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            formid = 1,
                            moduleid = 1
                        });
                });

            modelBuilder.Entity("Entity.Model.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("Permission", "segurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            description = "Permiso para ver todos los registros",
                            name = "GetAll"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            description = "Permiso para ver por id",
                            name = "GetById"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            description = "Permiso para crear un registro",
                            name = "Create"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            description = "Permiso para actualizar un registro",
                            name = "Update"
                        },
                        new
                        {
                            id = 5,
                            active = true,
                            description = "Permiso para eliminar logicamente un registro",
                            name = "DeleteLogic"
                        },
                        new
                        {
                            id = 6,
                            active = true,
                            description = "Permiso para eliminar permanentemente un registro",
                            name = "Delete"
                        },
                        new
                        {
                            id = 7,
                            active = true,
                            description = "Permiso para recuperar un registro",
                            name = "RecoverLogic"
                        });
                });

            modelBuilder.Entity("Entity.Model.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.ToTable("person", "persons");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            firstname = "Admin",
                            lastname = "Principal",
                            phonenumber = "111111111"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            firstname = "Usuario",
                            lastname = "Demo",
                            phonenumber = "222222222"
                        });
                });

            modelBuilder.Entity("Entity.Model.RolFormPermission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("formid")
                        .HasColumnType("int");

                    b.Property<int>("permissionid")
                        .HasColumnType("int");

                    b.Property<int>("rolid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("formid");

                    b.HasIndex("permissionid");

                    b.HasIndex("rolid");

                    b.ToTable("rolformpermission", "segurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            formid = 1,
                            permissionid = 1,
                            rolid = 1
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            formid = 1,
                            permissionid = 2,
                            rolid = 1
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            formid = 1,
                            permissionid = 3,
                            rolid = 1
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            formid = 1,
                            permissionid = 4,
                            rolid = 1
                        },
                        new
                        {
                            id = 5,
                            active = true,
                            formid = 1,
                            permissionid = 5,
                            rolid = 1
                        },
                        new
                        {
                            id = 6,
                            active = true,
                            formid = 1,
                            permissionid = 6,
                            rolid = 1
                        },
                        new
                        {
                            id = 7,
                            active = true,
                            formid = 1,
                            permissionid = 7,
                            rolid = 1
                        },
                        new
                        {
                            id = 8,
                            active = true,
                            formid = 1,
                            permissionid = 1,
                            rolid = 2
                        },
                        new
                        {
                            id = 9,
                            active = true,
                            formid = 1,
                            permissionid = 2,
                            rolid = 2
                        },
                        new
                        {
                            id = 10,
                            active = true,
                            formid = 1,
                            permissionid = 3,
                            rolid = 2
                        },
                        new
                        {
                            id = 11,
                            active = true,
                            formid = 1,
                            permissionid = 4,
                            rolid = 2
                        },
                        new
                        {
                            id = 12,
                            active = true,
                            formid = 1,
                            permissionid = 5,
                            rolid = 2
                        },
                        new
                        {
                            id = 13,
                            active = true,
                            formid = 2,
                            permissionid = 1,
                            rolid = 1
                        },
                        new
                        {
                            id = 14,
                            active = true,
                            formid = 2,
                            permissionid = 2,
                            rolid = 1
                        },
                        new
                        {
                            id = 15,
                            active = true,
                            formid = 2,
                            permissionid = 3,
                            rolid = 1
                        },
                        new
                        {
                            id = 16,
                            active = true,
                            formid = 2,
                            permissionid = 4,
                            rolid = 1
                        },
                        new
                        {
                            id = 17,
                            active = true,
                            formid = 2,
                            permissionid = 5,
                            rolid = 1
                        },
                        new
                        {
                            id = 18,
                            active = true,
                            formid = 2,
                            permissionid = 6,
                            rolid = 1
                        },
                        new
                        {
                            id = 19,
                            active = true,
                            formid = 2,
                            permissionid = 7,
                            rolid = 1
                        },
                        new
                        {
                            id = 20,
                            active = true,
                            formid = 2,
                            permissionid = 1,
                            rolid = 2
                        },
                        new
                        {
                            id = 21,
                            active = true,
                            formid = 2,
                            permissionid = 2,
                            rolid = 2
                        },
                        new
                        {
                            id = 22,
                            active = true,
                            formid = 2,
                            permissionid = 3,
                            rolid = 2
                        },
                        new
                        {
                            id = 23,
                            active = true,
                            formid = 2,
                            permissionid = 4,
                            rolid = 2
                        },
                        new
                        {
                            id = 24,
                            active = true,
                            formid = 2,
                            permissionid = 5,
                            rolid = 2
                        },
                        new
                        {
                            id = 25,
                            active = true,
                            formid = 3,
                            permissionid = 1,
                            rolid = 1
                        },
                        new
                        {
                            id = 26,
                            active = true,
                            formid = 3,
                            permissionid = 2,
                            rolid = 1
                        },
                        new
                        {
                            id = 27,
                            active = true,
                            formid = 3,
                            permissionid = 3,
                            rolid = 1
                        },
                        new
                        {
                            id = 28,
                            active = true,
                            formid = 3,
                            permissionid = 4,
                            rolid = 1
                        },
                        new
                        {
                            id = 29,
                            active = true,
                            formid = 3,
                            permissionid = 5,
                            rolid = 1
                        },
                        new
                        {
                            id = 30,
                            active = true,
                            formid = 3,
                            permissionid = 6,
                            rolid = 1
                        },
                        new
                        {
                            id = 31,
                            active = true,
                            formid = 3,
                            permissionid = 7,
                            rolid = 1
                        },
                        new
                        {
                            id = 32,
                            active = true,
                            formid = 3,
                            permissionid = 1,
                            rolid = 2
                        },
                        new
                        {
                            id = 33,
                            active = true,
                            formid = 3,
                            permissionid = 2,
                            rolid = 2
                        },
                        new
                        {
                            id = 34,
                            active = true,
                            formid = 3,
                            permissionid = 3,
                            rolid = 2
                        },
                        new
                        {
                            id = 35,
                            active = true,
                            formid = 3,
                            permissionid = 4,
                            rolid = 2
                        },
                        new
                        {
                            id = 36,
                            active = true,
                            formid = 3,
                            permissionid = 5,
                            rolid = 2
                        },
                        new
                        {
                            id = 37,
                            active = true,
                            formid = 4,
                            permissionid = 1,
                            rolid = 1
                        },
                        new
                        {
                            id = 38,
                            active = true,
                            formid = 4,
                            permissionid = 2,
                            rolid = 1
                        },
                        new
                        {
                            id = 39,
                            active = true,
                            formid = 4,
                            permissionid = 3,
                            rolid = 1
                        },
                        new
                        {
                            id = 40,
                            active = true,
                            formid = 4,
                            permissionid = 4,
                            rolid = 1
                        },
                        new
                        {
                            id = 41,
                            active = true,
                            formid = 4,
                            permissionid = 5,
                            rolid = 1
                        },
                        new
                        {
                            id = 42,
                            active = true,
                            formid = 4,
                            permissionid = 6,
                            rolid = 1
                        },
                        new
                        {
                            id = 43,
                            active = true,
                            formid = 4,
                            permissionid = 7,
                            rolid = 1
                        },
                        new
                        {
                            id = 44,
                            active = true,
                            formid = 4,
                            permissionid = 1,
                            rolid = 2
                        },
                        new
                        {
                            id = 45,
                            active = true,
                            formid = 4,
                            permissionid = 2,
                            rolid = 2
                        },
                        new
                        {
                            id = 46,
                            active = true,
                            formid = 4,
                            permissionid = 3,
                            rolid = 2
                        },
                        new
                        {
                            id = 47,
                            active = true,
                            formid = 4,
                            permissionid = 4,
                            rolid = 2
                        },
                        new
                        {
                            id = 48,
                            active = true,
                            formid = 4,
                            permissionid = 5,
                            rolid = 2
                        },
                        new
                        {
                            id = 49,
                            active = true,
                            formid = 5,
                            permissionid = 1,
                            rolid = 1
                        },
                        new
                        {
                            id = 50,
                            active = true,
                            formid = 5,
                            permissionid = 2,
                            rolid = 1
                        },
                        new
                        {
                            id = 51,
                            active = true,
                            formid = 5,
                            permissionid = 3,
                            rolid = 1
                        },
                        new
                        {
                            id = 52,
                            active = true,
                            formid = 5,
                            permissionid = 4,
                            rolid = 1
                        },
                        new
                        {
                            id = 53,
                            active = true,
                            formid = 5,
                            permissionid = 5,
                            rolid = 1
                        },
                        new
                        {
                            id = 54,
                            active = true,
                            formid = 5,
                            permissionid = 6,
                            rolid = 1
                        },
                        new
                        {
                            id = 55,
                            active = true,
                            formid = 5,
                            permissionid = 7,
                            rolid = 1
                        },
                        new
                        {
                            id = 56,
                            active = true,
                            formid = 5,
                            permissionid = 1,
                            rolid = 2
                        },
                        new
                        {
                            id = 57,
                            active = true,
                            formid = 5,
                            permissionid = 2,
                            rolid = 2
                        },
                        new
                        {
                            id = 58,
                            active = true,
                            formid = 5,
                            permissionid = 3,
                            rolid = 2
                        },
                        new
                        {
                            id = 59,
                            active = true,
                            formid = 5,
                            permissionid = 4,
                            rolid = 2
                        },
                        new
                        {
                            id = 60,
                            active = true,
                            formid = 5,
                            permissionid = 5,
                            rolid = 2
                        },
                        new
                        {
                            id = 61,
                            active = true,
                            formid = 6,
                            permissionid = 1,
                            rolid = 1
                        },
                        new
                        {
                            id = 62,
                            active = true,
                            formid = 6,
                            permissionid = 2,
                            rolid = 1
                        },
                        new
                        {
                            id = 63,
                            active = true,
                            formid = 6,
                            permissionid = 3,
                            rolid = 1
                        },
                        new
                        {
                            id = 64,
                            active = true,
                            formid = 6,
                            permissionid = 4,
                            rolid = 1
                        },
                        new
                        {
                            id = 65,
                            active = true,
                            formid = 6,
                            permissionid = 5,
                            rolid = 1
                        },
                        new
                        {
                            id = 66,
                            active = true,
                            formid = 6,
                            permissionid = 6,
                            rolid = 1
                        },
                        new
                        {
                            id = 67,
                            active = true,
                            formid = 6,
                            permissionid = 7,
                            rolid = 1
                        },
                        new
                        {
                            id = 68,
                            active = true,
                            formid = 6,
                            permissionid = 1,
                            rolid = 2
                        },
                        new
                        {
                            id = 69,
                            active = true,
                            formid = 6,
                            permissionid = 2,
                            rolid = 2
                        },
                        new
                        {
                            id = 70,
                            active = true,
                            formid = 6,
                            permissionid = 3,
                            rolid = 2
                        },
                        new
                        {
                            id = 71,
                            active = true,
                            formid = 6,
                            permissionid = 4,
                            rolid = 2
                        },
                        new
                        {
                            id = 72,
                            active = true,
                            formid = 6,
                            permissionid = 5,
                            rolid = 2
                        },
                        new
                        {
                            id = 73,
                            active = true,
                            formid = 7,
                            permissionid = 1,
                            rolid = 1
                        },
                        new
                        {
                            id = 74,
                            active = true,
                            formid = 7,
                            permissionid = 2,
                            rolid = 1
                        },
                        new
                        {
                            id = 75,
                            active = true,
                            formid = 7,
                            permissionid = 3,
                            rolid = 1
                        },
                        new
                        {
                            id = 76,
                            active = true,
                            formid = 7,
                            permissionid = 4,
                            rolid = 1
                        },
                        new
                        {
                            id = 77,
                            active = true,
                            formid = 7,
                            permissionid = 5,
                            rolid = 1
                        },
                        new
                        {
                            id = 78,
                            active = true,
                            formid = 7,
                            permissionid = 6,
                            rolid = 1
                        },
                        new
                        {
                            id = 79,
                            active = true,
                            formid = 7,
                            permissionid = 7,
                            rolid = 1
                        },
                        new
                        {
                            id = 80,
                            active = true,
                            formid = 7,
                            permissionid = 1,
                            rolid = 2
                        },
                        new
                        {
                            id = 81,
                            active = true,
                            formid = 7,
                            permissionid = 2,
                            rolid = 2
                        },
                        new
                        {
                            id = 82,
                            active = true,
                            formid = 7,
                            permissionid = 3,
                            rolid = 2
                        },
                        new
                        {
                            id = 83,
                            active = true,
                            formid = 7,
                            permissionid = 4,
                            rolid = 2
                        },
                        new
                        {
                            id = 84,
                            active = true,
                            formid = 7,
                            permissionid = 5,
                            rolid = 2
                        },
                        new
                        {
                            id = 85,
                            active = true,
                            formid = 8,
                            permissionid = 1,
                            rolid = 1
                        },
                        new
                        {
                            id = 86,
                            active = true,
                            formid = 8,
                            permissionid = 2,
                            rolid = 1
                        },
                        new
                        {
                            id = 87,
                            active = true,
                            formid = 8,
                            permissionid = 3,
                            rolid = 1
                        },
                        new
                        {
                            id = 88,
                            active = true,
                            formid = 8,
                            permissionid = 4,
                            rolid = 1
                        },
                        new
                        {
                            id = 89,
                            active = true,
                            formid = 8,
                            permissionid = 5,
                            rolid = 1
                        },
                        new
                        {
                            id = 90,
                            active = true,
                            formid = 8,
                            permissionid = 6,
                            rolid = 1
                        },
                        new
                        {
                            id = 91,
                            active = true,
                            formid = 8,
                            permissionid = 7,
                            rolid = 1
                        },
                        new
                        {
                            id = 92,
                            active = true,
                            formid = 8,
                            permissionid = 1,
                            rolid = 2
                        },
                        new
                        {
                            id = 93,
                            active = true,
                            formid = 8,
                            permissionid = 2,
                            rolid = 2
                        },
                        new
                        {
                            id = 94,
                            active = true,
                            formid = 8,
                            permissionid = 3,
                            rolid = 2
                        },
                        new
                        {
                            id = 95,
                            active = true,
                            formid = 8,
                            permissionid = 4,
                            rolid = 2
                        },
                        new
                        {
                            id = 96,
                            active = true,
                            formid = 8,
                            permissionid = 5,
                            rolid = 2
                        },
                        new
                        {
                            id = 97,
                            active = true,
                            formid = 9,
                            permissionid = 1,
                            rolid = 1
                        },
                        new
                        {
                            id = 98,
                            active = true,
                            formid = 9,
                            permissionid = 2,
                            rolid = 1
                        },
                        new
                        {
                            id = 99,
                            active = true,
                            formid = 9,
                            permissionid = 3,
                            rolid = 1
                        },
                        new
                        {
                            id = 100,
                            active = true,
                            formid = 9,
                            permissionid = 4,
                            rolid = 1
                        },
                        new
                        {
                            id = 101,
                            active = true,
                            formid = 9,
                            permissionid = 5,
                            rolid = 1
                        },
                        new
                        {
                            id = 102,
                            active = true,
                            formid = 9,
                            permissionid = 6,
                            rolid = 1
                        },
                        new
                        {
                            id = 103,
                            active = true,
                            formid = 9,
                            permissionid = 7,
                            rolid = 1
                        },
                        new
                        {
                            id = 104,
                            active = true,
                            formid = 9,
                            permissionid = 1,
                            rolid = 2
                        },
                        new
                        {
                            id = 105,
                            active = true,
                            formid = 9,
                            permissionid = 2,
                            rolid = 2
                        },
                        new
                        {
                            id = 106,
                            active = true,
                            formid = 9,
                            permissionid = 3,
                            rolid = 2
                        },
                        new
                        {
                            id = 107,
                            active = true,
                            formid = 9,
                            permissionid = 4,
                            rolid = 2
                        },
                        new
                        {
                            id = 108,
                            active = true,
                            formid = 9,
                            permissionid = 5,
                            rolid = 2
                        });
                });

            modelBuilder.Entity("Entity.Model.RolUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("rolid")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("rolid");

                    b.HasIndex("userid");

                    b.ToTable("roluser", "segurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            rolid = 1,
                            userid = 1
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            rolid = 2,
                            userid = 2
                        });
                });

            modelBuilder.Entity("Entity.Model.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("personid")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.HasIndex("personid");

                    b.ToTable("User", "segurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            email = "natiosoriopoveda@gmail.com",
                            password = "pecas",
                            personid = 1,
                            username = "admin"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            email = "marthapoveda579@gmail.com",
                            password = "usuario123",
                            personid = 2,
                            username = "usuario"
                        });
                });

            modelBuilder.Entity("Entity.Model.rol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("rol", "segurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            description = "Rol de administrador",
                            name = "Administrador"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            description = "Rol de usuario estándar",
                            name = "Usuario"
                        });
                });

            modelBuilder.Entity("Module", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("Module", "segurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            description = "Módulo de gestión",
                            name = "Gestión"
                        });
                });

            modelBuilder.Entity("Entity.Model.FormModule", b =>
                {
                    b.HasOne("Entity.Model.Form", "Form")
                        .WithMany("FormModules")
                        .HasForeignKey("formid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FormModule_Form");

                    b.HasOne("Module", "Module")
                        .WithMany("FormModules")
                        .HasForeignKey("moduleid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Module_FormModules");

                    b.Navigation("Form");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Entity.Model.RolFormPermission", b =>
                {
                    b.HasOne("Entity.Model.Form", "Form")
                        .WithMany("RolFormPermission")
                        .HasForeignKey("formid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolFormPermission_Form");

                    b.HasOne("Entity.Model.Permission", "Permission")
                        .WithMany("RolFormPermission")
                        .HasForeignKey("permissionid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolFormPermission_Permission");

                    b.HasOne("Entity.Model.rol", "Rol")
                        .WithMany("RolFormPermission")
                        .HasForeignKey("rolid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolFormPermission_Rol");

                    b.Navigation("Form");

                    b.Navigation("Permission");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Entity.Model.RolUser", b =>
                {
                    b.HasOne("Entity.Model.rol", "Rol")
                        .WithMany("RolUser")
                        .HasForeignKey("rolid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolUser_Rol");

                    b.HasOne("Entity.Model.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolUser_User");

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Model.User", b =>
                {
                    b.HasOne("Entity.Model.Person", "Person")
                        .WithMany("User")
                        .HasForeignKey("personid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Person_User");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entity.Model.Form", b =>
                {
                    b.Navigation("FormModules");

                    b.Navigation("RolFormPermission");
                });

            modelBuilder.Entity("Entity.Model.Permission", b =>
                {
                    b.Navigation("RolFormPermission");
                });

            modelBuilder.Entity("Entity.Model.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Model.User", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Entity.Model.rol", b =>
                {
                    b.Navigation("RolFormPermission");

                    b.Navigation("RolUser");
                });

            modelBuilder.Entity("Module", b =>
                {
                    b.Navigation("FormModules");
                });
#pragma warning restore 612, 618
        }
    }
}
